# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from coral.common.v1 import common_pb2 as coral_dot_common_dot_v1_dot_common__pb2
from coral.ingest.v1 import ingest_pb2 as coral_dot_ingest_dot_v1_dot_ingest__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in coral/ingest/v1/ingest_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class IngestServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InsertJsonl = channel.unary_unary(
                '/coral.ingest.v1.IngestService/InsertJsonl',
                request_serializer=coral_dot_ingest_dot_v1_dot_ingest__pb2.InsertJsonlRequest.SerializeToString,
                response_deserializer=coral_dot_ingest_dot_v1_dot_ingest__pb2.InsertResponse.FromString,
                _registered_method=True)
        self.InsertArrowIpc = channel.stream_unary(
                '/coral.ingest.v1.IngestService/InsertArrowIpc',
                request_serializer=coral_dot_ingest_dot_v1_dot_ingest__pb2.InsertArrowIpcStreamEvent.SerializeToString,
                response_deserializer=coral_dot_ingest_dot_v1_dot_ingest__pb2.InsertResponse.FromString,
                _registered_method=True)
        self.BatchInsertFiles = channel.unary_unary(
                '/coral.ingest.v1.IngestService/BatchInsertFiles',
                request_serializer=coral_dot_ingest_dot_v1_dot_ingest__pb2.BatchInsertFilesRequest.SerializeToString,
                response_deserializer=coral_dot_ingest_dot_v1_dot_ingest__pb2.BatchInsertFilesResponse.FromString,
                _registered_method=True)
        self.UpdateTableData = channel.unary_unary(
                '/coral.ingest.v1.IngestService/UpdateTableData',
                request_serializer=coral_dot_ingest_dot_v1_dot_ingest__pb2.UpdateTableDataRequest.SerializeToString,
                response_deserializer=coral_dot_common_dot_v1_dot_common__pb2.Empty.FromString,
                _registered_method=True)
        self.DeleteTableData = channel.unary_unary(
                '/coral.ingest.v1.IngestService/DeleteTableData',
                request_serializer=coral_dot_ingest_dot_v1_dot_ingest__pb2.DeleteTableDataRequest.SerializeToString,
                response_deserializer=coral_dot_common_dot_v1_dot_common__pb2.Empty.FromString,
                _registered_method=True)


class IngestServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def InsertJsonl(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InsertArrowIpc(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchInsertFiles(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateTableData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteTableData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IngestServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'InsertJsonl': grpc.unary_unary_rpc_method_handler(
                    servicer.InsertJsonl,
                    request_deserializer=coral_dot_ingest_dot_v1_dot_ingest__pb2.InsertJsonlRequest.FromString,
                    response_serializer=coral_dot_ingest_dot_v1_dot_ingest__pb2.InsertResponse.SerializeToString,
            ),
            'InsertArrowIpc': grpc.stream_unary_rpc_method_handler(
                    servicer.InsertArrowIpc,
                    request_deserializer=coral_dot_ingest_dot_v1_dot_ingest__pb2.InsertArrowIpcStreamEvent.FromString,
                    response_serializer=coral_dot_ingest_dot_v1_dot_ingest__pb2.InsertResponse.SerializeToString,
            ),
            'BatchInsertFiles': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchInsertFiles,
                    request_deserializer=coral_dot_ingest_dot_v1_dot_ingest__pb2.BatchInsertFilesRequest.FromString,
                    response_serializer=coral_dot_ingest_dot_v1_dot_ingest__pb2.BatchInsertFilesResponse.SerializeToString,
            ),
            'UpdateTableData': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateTableData,
                    request_deserializer=coral_dot_ingest_dot_v1_dot_ingest__pb2.UpdateTableDataRequest.FromString,
                    response_serializer=coral_dot_common_dot_v1_dot_common__pb2.Empty.SerializeToString,
            ),
            'DeleteTableData': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteTableData,
                    request_deserializer=coral_dot_ingest_dot_v1_dot_ingest__pb2.DeleteTableDataRequest.FromString,
                    response_serializer=coral_dot_common_dot_v1_dot_common__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'coral.ingest.v1.IngestService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('coral.ingest.v1.IngestService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class IngestService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def InsertJsonl(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/coral.ingest.v1.IngestService/InsertJsonl',
            coral_dot_ingest_dot_v1_dot_ingest__pb2.InsertJsonlRequest.SerializeToString,
            coral_dot_ingest_dot_v1_dot_ingest__pb2.InsertResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InsertArrowIpc(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/coral.ingest.v1.IngestService/InsertArrowIpc',
            coral_dot_ingest_dot_v1_dot_ingest__pb2.InsertArrowIpcStreamEvent.SerializeToString,
            coral_dot_ingest_dot_v1_dot_ingest__pb2.InsertResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchInsertFiles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/coral.ingest.v1.IngestService/BatchInsertFiles',
            coral_dot_ingest_dot_v1_dot_ingest__pb2.BatchInsertFilesRequest.SerializeToString,
            coral_dot_ingest_dot_v1_dot_ingest__pb2.BatchInsertFilesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateTableData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/coral.ingest.v1.IngestService/UpdateTableData',
            coral_dot_ingest_dot_v1_dot_ingest__pb2.UpdateTableDataRequest.SerializeToString,
            coral_dot_common_dot_v1_dot_common__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteTableData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/coral.ingest.v1.IngestService/DeleteTableData',
            coral_dot_ingest_dot_v1_dot_ingest__pb2.DeleteTableDataRequest.SerializeToString,
            coral_dot_common_dot_v1_dot_common__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
