# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from coral.segment.v1 import segment_pb2 as coral_dot_segment_dot_v1_dot_segment__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in coral/segment/v1/segment_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SegmentServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RetrySegments = channel.unary_unary(
                '/coral.segment.v1.SegmentService/RetrySegments',
                request_serializer=coral_dot_segment_dot_v1_dot_segment__pb2.RetrySegmentsRequest.SerializeToString,
                response_deserializer=coral_dot_segment_dot_v1_dot_segment__pb2.RetrySegmentsResponse.FromString,
                _registered_method=True)
        self.GetSegmentsStatus = channel.unary_unary(
                '/coral.segment.v1.SegmentService/GetSegmentsStatus',
                request_serializer=coral_dot_segment_dot_v1_dot_segment__pb2.GetSegmentsStatusRequest.SerializeToString,
                response_deserializer=coral_dot_segment_dot_v1_dot_segment__pb2.GetSegmentsStatusResponse.FromString,
                _registered_method=True)
        self.RebalancePlan = channel.unary_unary(
                '/coral.segment.v1.SegmentService/RebalancePlan',
                request_serializer=coral_dot_segment_dot_v1_dot_segment__pb2.RebalancePlanRequest.SerializeToString,
                response_deserializer=coral_dot_segment_dot_v1_dot_segment__pb2.RebalancePlanResponse.FromString,
                _registered_method=True)
        self.RebalanceCommit = channel.unary_unary(
                '/coral.segment.v1.SegmentService/RebalanceCommit',
                request_serializer=coral_dot_segment_dot_v1_dot_segment__pb2.RebalanceCommitRequest.SerializeToString,
                response_deserializer=coral_dot_segment_dot_v1_dot_segment__pb2.RebalanceCommitResponse.FromString,
                _registered_method=True)
        self.GetRebalanceStatus = channel.unary_unary(
                '/coral.segment.v1.SegmentService/GetRebalanceStatus',
                request_serializer=coral_dot_segment_dot_v1_dot_segment__pb2.GetRebalanceStatusRequest.SerializeToString,
                response_deserializer=coral_dot_segment_dot_v1_dot_segment__pb2.GetRebalanceStatusResponse.FromString,
                _registered_method=True)


class SegmentServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def RetrySegments(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSegmentsStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RebalancePlan(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RebalanceCommit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRebalanceStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SegmentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RetrySegments': grpc.unary_unary_rpc_method_handler(
                    servicer.RetrySegments,
                    request_deserializer=coral_dot_segment_dot_v1_dot_segment__pb2.RetrySegmentsRequest.FromString,
                    response_serializer=coral_dot_segment_dot_v1_dot_segment__pb2.RetrySegmentsResponse.SerializeToString,
            ),
            'GetSegmentsStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSegmentsStatus,
                    request_deserializer=coral_dot_segment_dot_v1_dot_segment__pb2.GetSegmentsStatusRequest.FromString,
                    response_serializer=coral_dot_segment_dot_v1_dot_segment__pb2.GetSegmentsStatusResponse.SerializeToString,
            ),
            'RebalancePlan': grpc.unary_unary_rpc_method_handler(
                    servicer.RebalancePlan,
                    request_deserializer=coral_dot_segment_dot_v1_dot_segment__pb2.RebalancePlanRequest.FromString,
                    response_serializer=coral_dot_segment_dot_v1_dot_segment__pb2.RebalancePlanResponse.SerializeToString,
            ),
            'RebalanceCommit': grpc.unary_unary_rpc_method_handler(
                    servicer.RebalanceCommit,
                    request_deserializer=coral_dot_segment_dot_v1_dot_segment__pb2.RebalanceCommitRequest.FromString,
                    response_serializer=coral_dot_segment_dot_v1_dot_segment__pb2.RebalanceCommitResponse.SerializeToString,
            ),
            'GetRebalanceStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRebalanceStatus,
                    request_deserializer=coral_dot_segment_dot_v1_dot_segment__pb2.GetRebalanceStatusRequest.FromString,
                    response_serializer=coral_dot_segment_dot_v1_dot_segment__pb2.GetRebalanceStatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'coral.segment.v1.SegmentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('coral.segment.v1.SegmentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SegmentService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RetrySegments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/coral.segment.v1.SegmentService/RetrySegments',
            coral_dot_segment_dot_v1_dot_segment__pb2.RetrySegmentsRequest.SerializeToString,
            coral_dot_segment_dot_v1_dot_segment__pb2.RetrySegmentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSegmentsStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/coral.segment.v1.SegmentService/GetSegmentsStatus',
            coral_dot_segment_dot_v1_dot_segment__pb2.GetSegmentsStatusRequest.SerializeToString,
            coral_dot_segment_dot_v1_dot_segment__pb2.GetSegmentsStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RebalancePlan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/coral.segment.v1.SegmentService/RebalancePlan',
            coral_dot_segment_dot_v1_dot_segment__pb2.RebalancePlanRequest.SerializeToString,
            coral_dot_segment_dot_v1_dot_segment__pb2.RebalancePlanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RebalanceCommit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/coral.segment.v1.SegmentService/RebalanceCommit',
            coral_dot_segment_dot_v1_dot_segment__pb2.RebalanceCommitRequest.SerializeToString,
            coral_dot_segment_dot_v1_dot_segment__pb2.RebalanceCommitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRebalanceStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/coral.segment.v1.SegmentService/GetRebalanceStatus',
            coral_dot_segment_dot_v1_dot_segment__pb2.GetRebalanceStatusRequest.SerializeToString,
            coral_dot_segment_dot_v1_dot_segment__pb2.GetRebalanceStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
