# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: coral/health/v1/health.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'coral/health/v1/health.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x63oral/health/v1/health.proto\x12\x0f\x63oral.health.v1\"\x14\n\x12HealthCheckRequest\";\n\x13HealthCheckResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x13\n\x0bvisit_count\x18\x02 \x01(\x05\x32\x63\n\rHealthService\x12R\n\x05\x43heck\x12#.coral.health.v1.HealthCheckRequest\x1a$.coral.health.v1.HealthCheckResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'coral.health.v1.health_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HEALTHCHECKREQUEST']._serialized_start=49
  _globals['_HEALTHCHECKREQUEST']._serialized_end=69
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=71
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=130
  _globals['_HEALTHSERVICE']._serialized_start=132
  _globals['_HEALTHSERVICE']._serialized_end=231
# @@protoc_insertion_point(module_scope)
