# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from coral.query.v1 import query_pb2 as coral_dot_query_dot_v1_dot_query__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in coral/query/v1/query_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class QueryServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ScanTableData = channel.unary_stream(
                '/coral.query.v1.QueryService/ScanTableData',
                request_serializer=coral_dot_query_dot_v1_dot_query__pb2.ScanTableDataRequest.SerializeToString,
                response_deserializer=coral_dot_query_dot_v1_dot_query__pb2.ResultStreamEvent.FromString,
                _registered_method=True)
        self.VectorSearch = channel.unary_stream(
                '/coral.query.v1.QueryService/VectorSearch',
                request_serializer=coral_dot_query_dot_v1_dot_query__pb2.VectorSearchRequest.SerializeToString,
                response_deserializer=coral_dot_query_dot_v1_dot_query__pb2.ResultStreamEvent.FromString,
                _registered_method=True)
        self.HybridSearch = channel.unary_stream(
                '/coral.query.v1.QueryService/HybridSearch',
                request_serializer=coral_dot_query_dot_v1_dot_query__pb2.HybridSearchRequest.SerializeToString,
                response_deserializer=coral_dot_query_dot_v1_dot_query__pb2.ResultStreamEvent.FromString,
                _registered_method=True)
        self.VectorSearchExactKnn = channel.unary_stream(
                '/coral.query.v1.QueryService/VectorSearchExactKnn',
                request_serializer=coral_dot_query_dot_v1_dot_query__pb2.VectorSearchExactKnnRequest.SerializeToString,
                response_deserializer=coral_dot_query_dot_v1_dot_query__pb2.ResultStreamEvent.FromString,
                _registered_method=True)
        self.DataPlan = channel.unary_unary(
                '/coral.query.v1.QueryService/DataPlan',
                request_serializer=coral_dot_query_dot_v1_dot_query__pb2.DataPlanRequest.SerializeToString,
                response_deserializer=coral_dot_query_dot_v1_dot_query__pb2.DataPlanResponse.FromString,
                _registered_method=True)


class QueryServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def ScanTableData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VectorSearch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HybridSearch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VectorSearchExactKnn(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DataPlan(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_QueryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ScanTableData': grpc.unary_stream_rpc_method_handler(
                    servicer.ScanTableData,
                    request_deserializer=coral_dot_query_dot_v1_dot_query__pb2.ScanTableDataRequest.FromString,
                    response_serializer=coral_dot_query_dot_v1_dot_query__pb2.ResultStreamEvent.SerializeToString,
            ),
            'VectorSearch': grpc.unary_stream_rpc_method_handler(
                    servicer.VectorSearch,
                    request_deserializer=coral_dot_query_dot_v1_dot_query__pb2.VectorSearchRequest.FromString,
                    response_serializer=coral_dot_query_dot_v1_dot_query__pb2.ResultStreamEvent.SerializeToString,
            ),
            'HybridSearch': grpc.unary_stream_rpc_method_handler(
                    servicer.HybridSearch,
                    request_deserializer=coral_dot_query_dot_v1_dot_query__pb2.HybridSearchRequest.FromString,
                    response_serializer=coral_dot_query_dot_v1_dot_query__pb2.ResultStreamEvent.SerializeToString,
            ),
            'VectorSearchExactKnn': grpc.unary_stream_rpc_method_handler(
                    servicer.VectorSearchExactKnn,
                    request_deserializer=coral_dot_query_dot_v1_dot_query__pb2.VectorSearchExactKnnRequest.FromString,
                    response_serializer=coral_dot_query_dot_v1_dot_query__pb2.ResultStreamEvent.SerializeToString,
            ),
            'DataPlan': grpc.unary_unary_rpc_method_handler(
                    servicer.DataPlan,
                    request_deserializer=coral_dot_query_dot_v1_dot_query__pb2.DataPlanRequest.FromString,
                    response_serializer=coral_dot_query_dot_v1_dot_query__pb2.DataPlanResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'coral.query.v1.QueryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('coral.query.v1.QueryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class QueryService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ScanTableData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/coral.query.v1.QueryService/ScanTableData',
            coral_dot_query_dot_v1_dot_query__pb2.ScanTableDataRequest.SerializeToString,
            coral_dot_query_dot_v1_dot_query__pb2.ResultStreamEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VectorSearch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/coral.query.v1.QueryService/VectorSearch',
            coral_dot_query_dot_v1_dot_query__pb2.VectorSearchRequest.SerializeToString,
            coral_dot_query_dot_v1_dot_query__pb2.ResultStreamEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HybridSearch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/coral.query.v1.QueryService/HybridSearch',
            coral_dot_query_dot_v1_dot_query__pb2.HybridSearchRequest.SerializeToString,
            coral_dot_query_dot_v1_dot_query__pb2.ResultStreamEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VectorSearchExactKnn(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/coral.query.v1.QueryService/VectorSearchExactKnn',
            coral_dot_query_dot_v1_dot_query__pb2.VectorSearchExactKnnRequest.SerializeToString,
            coral_dot_query_dot_v1_dot_query__pb2.ResultStreamEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DataPlan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/coral.query.v1.QueryService/DataPlan',
            coral_dot_query_dot_v1_dot_query__pb2.DataPlanRequest.SerializeToString,
            coral_dot_query_dot_v1_dot_query__pb2.DataPlanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
