# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from coral.table.v1 import table_pb2 as coral_dot_table_dot_v1_dot_table__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in coral/table/v1/table_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TableServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListTables = channel.unary_unary(
                '/coral.table.v1.TableService/ListTables',
                request_serializer=coral_dot_table_dot_v1_dot_table__pb2.ListTablesRequest.SerializeToString,
                response_deserializer=coral_dot_table_dot_v1_dot_table__pb2.ListTablesResponse.FromString,
                _registered_method=True)
        self.GetTable = channel.unary_unary(
                '/coral.table.v1.TableService/GetTable',
                request_serializer=coral_dot_table_dot_v1_dot_table__pb2.GetTableRequest.SerializeToString,
                response_deserializer=coral_dot_table_dot_v1_dot_table__pb2.GetTableResponse.FromString,
                _registered_method=True)
        self.CreateTable = channel.unary_unary(
                '/coral.table.v1.TableService/CreateTable',
                request_serializer=coral_dot_table_dot_v1_dot_table__pb2.CreateTableRequest.SerializeToString,
                response_deserializer=coral_dot_table_dot_v1_dot_table__pb2.CreateTableResponse.FromString,
                _registered_method=True)
        self.DeleteTable = channel.unary_unary(
                '/coral.table.v1.TableService/DeleteTable',
                request_serializer=coral_dot_table_dot_v1_dot_table__pb2.DeleteTableRequest.SerializeToString,
                response_deserializer=coral_dot_table_dot_v1_dot_table__pb2.DeleteTableResponse.FromString,
                _registered_method=True)
        self.GetCreateStatus = channel.unary_unary(
                '/coral.table.v1.TableService/GetCreateStatus',
                request_serializer=coral_dot_table_dot_v1_dot_table__pb2.GetCreateStatusRequest.SerializeToString,
                response_deserializer=coral_dot_table_dot_v1_dot_table__pb2.GetCreateStatusResponse.FromString,
                _registered_method=True)
        self.ActiveSetFlush = channel.unary_unary(
                '/coral.table.v1.TableService/ActiveSetFlush',
                request_serializer=coral_dot_table_dot_v1_dot_table__pb2.ActiveSetFlushRequest.SerializeToString,
                response_deserializer=coral_dot_table_dot_v1_dot_table__pb2.ActiveSetFlushResponse.FromString,
                _registered_method=True)
        self.GetIndexedRowCount = channel.unary_unary(
                '/coral.table.v1.TableService/GetIndexedRowCount',
                request_serializer=coral_dot_table_dot_v1_dot_table__pb2.GetIndexedRowCountRequest.SerializeToString,
                response_deserializer=coral_dot_table_dot_v1_dot_table__pb2.GetIndexedRowCountResponse.FromString,
                _registered_method=True)


class TableServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def ListTables(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateTable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteTable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCreateStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ActiveSetFlush(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetIndexedRowCount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TableServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListTables': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTables,
                    request_deserializer=coral_dot_table_dot_v1_dot_table__pb2.ListTablesRequest.FromString,
                    response_serializer=coral_dot_table_dot_v1_dot_table__pb2.ListTablesResponse.SerializeToString,
            ),
            'GetTable': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTable,
                    request_deserializer=coral_dot_table_dot_v1_dot_table__pb2.GetTableRequest.FromString,
                    response_serializer=coral_dot_table_dot_v1_dot_table__pb2.GetTableResponse.SerializeToString,
            ),
            'CreateTable': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateTable,
                    request_deserializer=coral_dot_table_dot_v1_dot_table__pb2.CreateTableRequest.FromString,
                    response_serializer=coral_dot_table_dot_v1_dot_table__pb2.CreateTableResponse.SerializeToString,
            ),
            'DeleteTable': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteTable,
                    request_deserializer=coral_dot_table_dot_v1_dot_table__pb2.DeleteTableRequest.FromString,
                    response_serializer=coral_dot_table_dot_v1_dot_table__pb2.DeleteTableResponse.SerializeToString,
            ),
            'GetCreateStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCreateStatus,
                    request_deserializer=coral_dot_table_dot_v1_dot_table__pb2.GetCreateStatusRequest.FromString,
                    response_serializer=coral_dot_table_dot_v1_dot_table__pb2.GetCreateStatusResponse.SerializeToString,
            ),
            'ActiveSetFlush': grpc.unary_unary_rpc_method_handler(
                    servicer.ActiveSetFlush,
                    request_deserializer=coral_dot_table_dot_v1_dot_table__pb2.ActiveSetFlushRequest.FromString,
                    response_serializer=coral_dot_table_dot_v1_dot_table__pb2.ActiveSetFlushResponse.SerializeToString,
            ),
            'GetIndexedRowCount': grpc.unary_unary_rpc_method_handler(
                    servicer.GetIndexedRowCount,
                    request_deserializer=coral_dot_table_dot_v1_dot_table__pb2.GetIndexedRowCountRequest.FromString,
                    response_serializer=coral_dot_table_dot_v1_dot_table__pb2.GetIndexedRowCountResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'coral.table.v1.TableService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('coral.table.v1.TableService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TableService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListTables(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/coral.table.v1.TableService/ListTables',
            coral_dot_table_dot_v1_dot_table__pb2.ListTablesRequest.SerializeToString,
            coral_dot_table_dot_v1_dot_table__pb2.ListTablesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/coral.table.v1.TableService/GetTable',
            coral_dot_table_dot_v1_dot_table__pb2.GetTableRequest.SerializeToString,
            coral_dot_table_dot_v1_dot_table__pb2.GetTableResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateTable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/coral.table.v1.TableService/CreateTable',
            coral_dot_table_dot_v1_dot_table__pb2.CreateTableRequest.SerializeToString,
            coral_dot_table_dot_v1_dot_table__pb2.CreateTableResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteTable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/coral.table.v1.TableService/DeleteTable',
            coral_dot_table_dot_v1_dot_table__pb2.DeleteTableRequest.SerializeToString,
            coral_dot_table_dot_v1_dot_table__pb2.DeleteTableResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCreateStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/coral.table.v1.TableService/GetCreateStatus',
            coral_dot_table_dot_v1_dot_table__pb2.GetCreateStatusRequest.SerializeToString,
            coral_dot_table_dot_v1_dot_table__pb2.GetCreateStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ActiveSetFlush(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/coral.table.v1.TableService/ActiveSetFlush',
            coral_dot_table_dot_v1_dot_table__pb2.ActiveSetFlushRequest.SerializeToString,
            coral_dot_table_dot_v1_dot_table__pb2.ActiveSetFlushResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetIndexedRowCount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/coral.table.v1.TableService/GetIndexedRowCount',
            coral_dot_table_dot_v1_dot_table__pb2.GetIndexedRowCountRequest.SerializeToString,
            coral_dot_table_dot_v1_dot_table__pb2.GetIndexedRowCountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
