# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from coral.catalog.v1 import catalog_pb2 as coral_dot_catalog_dot_v1_dot_catalog__pb2
from coral.common.v1 import common_pb2 as coral_dot_common_dot_v1_dot_common__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in coral/catalog/v1/catalog_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CatalogAdminServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCatalogStorageDump = channel.unary_unary(
                '/coral.catalog.v1.CatalogAdminService/GetCatalogStorageDump',
                request_serializer=coral_dot_catalog_dot_v1_dot_catalog__pb2.GetCatalogStorageDumpRequest.SerializeToString,
                response_deserializer=coral_dot_catalog_dot_v1_dot_catalog__pb2.GetCatalogStorageDumpResponse.FromString,
                _registered_method=True)
        self.GetCatalogCacheDump = channel.unary_unary(
                '/coral.catalog.v1.CatalogAdminService/GetCatalogCacheDump',
                request_serializer=coral_dot_catalog_dot_v1_dot_catalog__pb2.GetCatalogCacheDumpRequest.SerializeToString,
                response_deserializer=coral_dot_catalog_dot_v1_dot_catalog__pb2.GetCatalogCacheDumpResponse.FromString,
                _registered_method=True)
        self.GetCatalogCacheStats = channel.unary_unary(
                '/coral.catalog.v1.CatalogAdminService/GetCatalogCacheStats',
                request_serializer=coral_dot_common_dot_v1_dot_common__pb2.Empty.SerializeToString,
                response_deserializer=coral_dot_catalog_dot_v1_dot_catalog__pb2.GetCatalogCacheStatsResponse.FromString,
                _registered_method=True)
        self.GetCatalogCacheConfig = channel.unary_unary(
                '/coral.catalog.v1.CatalogAdminService/GetCatalogCacheConfig',
                request_serializer=coral_dot_common_dot_v1_dot_common__pb2.Empty.SerializeToString,
                response_deserializer=coral_dot_catalog_dot_v1_dot_catalog__pb2.GetCatalogCacheConfigResponse.FromString,
                _registered_method=True)
        self.RefreshCatalogCache = channel.unary_unary(
                '/coral.catalog.v1.CatalogAdminService/RefreshCatalogCache',
                request_serializer=coral_dot_common_dot_v1_dot_common__pb2.Empty.SerializeToString,
                response_deserializer=coral_dot_catalog_dot_v1_dot_catalog__pb2.RefreshCatalogCacheResponse.FromString,
                _registered_method=True)
        self.InvalidateCatalogCache = channel.unary_unary(
                '/coral.catalog.v1.CatalogAdminService/InvalidateCatalogCache',
                request_serializer=coral_dot_catalog_dot_v1_dot_catalog__pb2.InvalidateCatalogCacheRequest.SerializeToString,
                response_deserializer=coral_dot_catalog_dot_v1_dot_catalog__pb2.InvalidateCatalogCacheResponse.FromString,
                _registered_method=True)


class CatalogAdminServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def GetCatalogStorageDump(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCatalogCacheDump(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCatalogCacheStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCatalogCacheConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RefreshCatalogCache(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InvalidateCatalogCache(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CatalogAdminServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetCatalogStorageDump': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCatalogStorageDump,
                    request_deserializer=coral_dot_catalog_dot_v1_dot_catalog__pb2.GetCatalogStorageDumpRequest.FromString,
                    response_serializer=coral_dot_catalog_dot_v1_dot_catalog__pb2.GetCatalogStorageDumpResponse.SerializeToString,
            ),
            'GetCatalogCacheDump': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCatalogCacheDump,
                    request_deserializer=coral_dot_catalog_dot_v1_dot_catalog__pb2.GetCatalogCacheDumpRequest.FromString,
                    response_serializer=coral_dot_catalog_dot_v1_dot_catalog__pb2.GetCatalogCacheDumpResponse.SerializeToString,
            ),
            'GetCatalogCacheStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCatalogCacheStats,
                    request_deserializer=coral_dot_common_dot_v1_dot_common__pb2.Empty.FromString,
                    response_serializer=coral_dot_catalog_dot_v1_dot_catalog__pb2.GetCatalogCacheStatsResponse.SerializeToString,
            ),
            'GetCatalogCacheConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCatalogCacheConfig,
                    request_deserializer=coral_dot_common_dot_v1_dot_common__pb2.Empty.FromString,
                    response_serializer=coral_dot_catalog_dot_v1_dot_catalog__pb2.GetCatalogCacheConfigResponse.SerializeToString,
            ),
            'RefreshCatalogCache': grpc.unary_unary_rpc_method_handler(
                    servicer.RefreshCatalogCache,
                    request_deserializer=coral_dot_common_dot_v1_dot_common__pb2.Empty.FromString,
                    response_serializer=coral_dot_catalog_dot_v1_dot_catalog__pb2.RefreshCatalogCacheResponse.SerializeToString,
            ),
            'InvalidateCatalogCache': grpc.unary_unary_rpc_method_handler(
                    servicer.InvalidateCatalogCache,
                    request_deserializer=coral_dot_catalog_dot_v1_dot_catalog__pb2.InvalidateCatalogCacheRequest.FromString,
                    response_serializer=coral_dot_catalog_dot_v1_dot_catalog__pb2.InvalidateCatalogCacheResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'coral.catalog.v1.CatalogAdminService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('coral.catalog.v1.CatalogAdminService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CatalogAdminService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetCatalogStorageDump(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/coral.catalog.v1.CatalogAdminService/GetCatalogStorageDump',
            coral_dot_catalog_dot_v1_dot_catalog__pb2.GetCatalogStorageDumpRequest.SerializeToString,
            coral_dot_catalog_dot_v1_dot_catalog__pb2.GetCatalogStorageDumpResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCatalogCacheDump(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/coral.catalog.v1.CatalogAdminService/GetCatalogCacheDump',
            coral_dot_catalog_dot_v1_dot_catalog__pb2.GetCatalogCacheDumpRequest.SerializeToString,
            coral_dot_catalog_dot_v1_dot_catalog__pb2.GetCatalogCacheDumpResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCatalogCacheStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/coral.catalog.v1.CatalogAdminService/GetCatalogCacheStats',
            coral_dot_common_dot_v1_dot_common__pb2.Empty.SerializeToString,
            coral_dot_catalog_dot_v1_dot_catalog__pb2.GetCatalogCacheStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCatalogCacheConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/coral.catalog.v1.CatalogAdminService/GetCatalogCacheConfig',
            coral_dot_common_dot_v1_dot_common__pb2.Empty.SerializeToString,
            coral_dot_catalog_dot_v1_dot_catalog__pb2.GetCatalogCacheConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RefreshCatalogCache(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/coral.catalog.v1.CatalogAdminService/RefreshCatalogCache',
            coral_dot_common_dot_v1_dot_common__pb2.Empty.SerializeToString,
            coral_dot_catalog_dot_v1_dot_catalog__pb2.RefreshCatalogCacheResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InvalidateCatalogCache(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/coral.catalog.v1.CatalogAdminService/InvalidateCatalogCache',
            coral_dot_catalog_dot_v1_dot_catalog__pb2.InvalidateCatalogCacheRequest.SerializeToString,
            coral_dot_catalog_dot_v1_dot_catalog__pb2.InvalidateCatalogCacheResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
