# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: coral/storage/v1/storage.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'coral/storage/v1/storage.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1e\x63oral/storage/v1/storage.proto\x12\x10\x63oral.storage.v1\"i\n\x17\x43loudStorageCredentials\x12\x17\n\naccess_key\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x17\n\nsecret_key\x18\x02 \x01(\tH\x01\x88\x01\x01\x42\r\n\x0b_access_keyB\r\n\x0b_secret_key\"\xbd\x01\n\x13\x43loudStorageOptions\x12\x13\n\x06region\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x15\n\x08\x65ndpoint\x18\x02 \x01(\tH\x01\x88\x01\x01\x12!\n\x14virtual_hosted_style\x18\x03 \x01(\x08H\x02\x88\x01\x01\x12\x17\n\nallow_http\x18\x04 \x01(\x08H\x03\x88\x01\x01\x42\t\n\x07_regionB\x0b\n\t_endpointB\x17\n\x15_virtual_hosted_styleB\r\n\x0b_allow_http\"\x82\x02\n\rStorageConfig\x12\x33\n\x0cstorage_type\x18\x01 \x01(\x0e\x32\x1d.coral.storage.v1.StorageType\x12\x13\n\x06\x62ucket\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\x43\n\x0b\x63redentials\x18\x03 \x01(\x0b\x32).coral.storage.v1.CloudStorageCredentialsH\x01\x88\x01\x01\x12;\n\x07options\x18\x04 \x01(\x0b\x32%.coral.storage.v1.CloudStorageOptionsH\x02\x88\x01\x01\x42\t\n\x07_bucketB\x0e\n\x0c_credentialsB\n\n\x08_options\"g\n\x05Paths\x12\r\n\x05paths\x18\x01 \x03(\t\x12<\n\x0estorage_config\x18\x02 \x01(\x0b\x32\x1f.coral.storage.v1.StorageConfigH\x00\x88\x01\x01\x42\x11\n\x0f_storage_config*Y\n\nFileFormat\x12\x1b\n\x17\x46ILE_FORMAT_UNSPECIFIED\x10\x00\x12\x15\n\x11\x46ILE_FORMAT_JSONL\x10\x01\x12\x17\n\x13\x46ILE_FORMAT_PARQUET\x10\x02*\xeb\x01\n\x0bStorageType\x12\x1c\n\x18STORAGE_TYPE_UNSPECIFIED\x10\x00\x12\x16\n\x12STORAGE_TYPE_LOCAL\x10\x01\x12\x14\n\x10STORAGE_TYPE_AWS\x10\x02\x12\x13\n\x0fSTORAGE_TYPE_S3\x10\x03\x12\x14\n\x10STORAGE_TYPE_GCP\x10\x04\x12\x16\n\x12STORAGE_TYPE_AZURE\x10\x05\x12\x15\n\x11STORAGE_TYPE_CEPH\x10\x06\x12\x16\n\x12STORAGE_TYPE_MINIO\x10\x07\x12\x1e\n\x1aSTORAGE_TYPE_S3_COMPATIBLE\x10\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'coral.storage.v1.storage_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FILEFORMAT']._serialized_start=717
  _globals['_FILEFORMAT']._serialized_end=806
  _globals['_STORAGETYPE']._serialized_start=809
  _globals['_STORAGETYPE']._serialized_end=1044
  _globals['_CLOUDSTORAGECREDENTIALS']._serialized_start=52
  _globals['_CLOUDSTORAGECREDENTIALS']._serialized_end=157
  _globals['_CLOUDSTORAGEOPTIONS']._serialized_start=160
  _globals['_CLOUDSTORAGEOPTIONS']._serialized_end=349
  _globals['_STORAGECONFIG']._serialized_start=352
  _globals['_STORAGECONFIG']._serialized_end=610
  _globals['_PATHS']._serialized_start=612
  _globals['_PATHS']._serialized_end=715
# @@protoc_insertion_point(module_scope)
