# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: coral/common/v1/common.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'coral/common/v1/common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x63oral/common/v1/common.proto\x12\x0f\x63oral.common.v1\"l\n\x0eRequestMetrics\x12\x19\n\x0c\x65lapsed_time\x18\x01 \x01(\x02H\x00\x88\x01\x01\x12\x1b\n\x0erss_peak_bytes\x18\x02 \x01(\x04H\x01\x88\x01\x01\x42\x0f\n\r_elapsed_timeB\x11\n\x0f_rss_peak_bytes\"\'\n\x0b\x41rrowSchema\x12\x18\n\x10\x61rrow_schema_ipc\x18\x01 \x01(\x0c\"r\n\x0bScalarValue\x12\x14\n\nbool_value\x18\x01 \x01(\x08H\x00\x12\x15\n\x0bint64_value\x18\x02 \x01(\x03H\x00\x12\x16\n\x0c\x64ouble_value\x18\x03 \x01(\x01H\x00\x12\x16\n\x0cstring_value\x18\x04 \x01(\tH\x00\x42\x06\n\x04kind\"\x0b\n\tNullValue\"<\n\x0b\x44ynamicList\x12-\n\x06values\x18\x01 \x03(\x0b\x32\x1d.coral.common.v1.DynamicValue\"\x99\x01\n\rDynamicStruct\x12:\n\x06\x66ields\x18\x01 \x03(\x0b\x32*.coral.common.v1.DynamicStruct.FieldsEntry\x1aL\n\x0b\x46ieldsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12,\n\x05value\x18\x02 \x01(\x0b\x32\x1d.coral.common.v1.DynamicValue:\x02\x38\x01\"\x91\x02\n\x0c\x44ynamicValue\x12\x30\n\nnull_value\x18\x01 \x01(\x0b\x32\x1a.coral.common.v1.NullValueH\x00\x12\x14\n\nbool_value\x18\x02 \x01(\x08H\x00\x12\x15\n\x0bint64_value\x18\x03 \x01(\x03H\x00\x12\x16\n\x0c\x64ouble_value\x18\x04 \x01(\x01H\x00\x12\x16\n\x0cstring_value\x18\x05 \x01(\tH\x00\x12\x32\n\nlist_value\x18\x06 \x01(\x0b\x32\x1c.coral.common.v1.DynamicListH\x00\x12\x36\n\x0cstruct_value\x18\x07 \x01(\x0b\x32\x1e.coral.common.v1.DynamicStructH\x00\x42\x06\n\x04kind\"\x1e\n\x0cStringValues\x12\x0e\n\x06values\x18\x01 \x03(\t\"\x1d\n\x0bInt64Values\x12\x0e\n\x06values\x18\x01 \x03(\x03\"\x07\n\x05\x45mptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'coral.common.v1.common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DYNAMICSTRUCT_FIELDSENTRY']._loaded_options = None
  _globals['_DYNAMICSTRUCT_FIELDSENTRY']._serialized_options = b'8\001'
  _globals['_REQUESTMETRICS']._serialized_start=49
  _globals['_REQUESTMETRICS']._serialized_end=157
  _globals['_ARROWSCHEMA']._serialized_start=159
  _globals['_ARROWSCHEMA']._serialized_end=198
  _globals['_SCALARVALUE']._serialized_start=200
  _globals['_SCALARVALUE']._serialized_end=314
  _globals['_NULLVALUE']._serialized_start=316
  _globals['_NULLVALUE']._serialized_end=327
  _globals['_DYNAMICLIST']._serialized_start=329
  _globals['_DYNAMICLIST']._serialized_end=389
  _globals['_DYNAMICSTRUCT']._serialized_start=392
  _globals['_DYNAMICSTRUCT']._serialized_end=545
  _globals['_DYNAMICSTRUCT_FIELDSENTRY']._serialized_start=469
  _globals['_DYNAMICSTRUCT_FIELDSENTRY']._serialized_end=545
  _globals['_DYNAMICVALUE']._serialized_start=548
  _globals['_DYNAMICVALUE']._serialized_end=821
  _globals['_STRINGVALUES']._serialized_start=823
  _globals['_STRINGVALUES']._serialized_end=853
  _globals['_INT64VALUES']._serialized_start=855
  _globals['_INT64VALUES']._serialized_end=884
  _globals['_EMPTY']._serialized_start=886
  _globals['_EMPTY']._serialized_end=893
# @@protoc_insertion_point(module_scope)
